# Telling Docker what base image to use for the application
FROM python:3
FROM python:3.7-slim
FROM python:3.8
FROM python:3.8-slim
FROM python:3.8-slim-buster
FROM python:3.9
FROM python:3.9-slim
FROM python:3.9-slim-buster
FROM python:3.11
FROM python:3.11-alpine



